export const candidateExportFixture = {
  id: 'c1',
  firstName: 'Camille',
  lastName: 'Durand',
  email: null,
  phone: null,
  address: null,
  city: 'Lyon',
  postalCode: '69003',
  mobilityRadiusKm: null,
  mobilityNotes: null,
  availableFrom: null,
  notes: null,
  cvSummary: null,
  anonymizedProfile: null,
  createdAt: new Date('2024-06-01T10:00:00Z'),
  updatedAt: new Date('2024-06-02T10:00:00Z'),
  jobTitle: { name: 'Pharmacien' },
  referent: { name: 'Recruteur' },
  softwares: [],
  contractPreferences: [],
  missions: [],
}
