export const profileFixture = {
  id: 'c1',
  firstName: 'Camille',
  lastName: 'Durand',
  email: null,
  phone: null,
  address: null,
  city: 'Lyon',
  postalCode: null,
  latitude: null,
  longitude: null,
  jobTitleId: 'jt1',
  status: 'NOUVEAU' as const,
  salaryExpectations: null,
  salaryMin: null,
  salaryMax: null,
  mobilityRadiusKm: null,
  mobilityNotes: null,
  availableFrom: null,
  notes: null,
  referentId: 'u1',
  cvUrl: null,
  cvSummary: null,
  anonymizedProfile: null,
  consentGivenAt: null,
  consentSource: null,
  createdAt: new Date('2026-01-15'),
  updatedAt: new Date('2026-01-15'),
  deletedAt: null,
  jobTitle: { id: 'jt1', name: 'Pharmacien' },
  referent: { id: 'u1', name: 'Recruteur' },
  softwares: [],
  contractPreferences: [],
  missions: [],
}
