import {
  PILOTAGE_CHART_CUMUL,
  PILOTAGE_CHART_CUMUL_SEUIL,
  PILOTAGE_CHART_INTERIM,
  PILOTAGE_CHART_OBJECTIF,
  PILOTAGE_CHART_PLACEMENT,
  PILOTAGE_CHART_SEUIL,
  FACTURATION_CHART_MARGE,
} from '@/view-models/facturation-chart-copy'
import {
  FACTURATION_CHART_CUMUL_STROKE,
  FACTURATION_CHART_INTERIM_FILL,
  FACTURATION_CHART_OBJECTIF_STROKE,
  FACTURATION_CHART_PLACEMENT_FILL,
  FACTURATION_CHART_SEUIL_STROKE,
} from '@/view-models/facturation-chart-style'

export const PILOTAGE_CA_BARS = [
  { dataKey: 'placementCa', name: PILOTAGE_CHART_PLACEMENT, fill: FACTURATION_CHART_PLACEMENT_FILL, stackId: 'ca' },
  { dataKey: 'interimCa', name: PILOTAGE_CHART_INTERIM, fill: FACTURATION_CHART_INTERIM_FILL, stackId: 'ca' },
]

export const PILOTAGE_CA_LINES = [
  { dataKey: 'objectif', name: PILOTAGE_CHART_OBJECTIF, stroke: FACTURATION_CHART_OBJECTIF_STROKE },
  { dataKey: 'cumul', name: PILOTAGE_CHART_CUMUL, stroke: FACTURATION_CHART_CUMUL_STROKE },
]

export const PILOTAGE_MARGE_BARS = [
  { dataKey: 'marge', name: FACTURATION_CHART_MARGE, fill: FACTURATION_CHART_PLACEMENT_FILL },
]

export const PILOTAGE_MARGE_LINES = [
  { dataKey: 'seuil', name: PILOTAGE_CHART_SEUIL, stroke: FACTURATION_CHART_SEUIL_STROKE },
  { dataKey: 'cumul', name: PILOTAGE_CHART_CUMUL, stroke: FACTURATION_CHART_CUMUL_STROKE },
  { dataKey: 'cumulSeuil', name: PILOTAGE_CHART_CUMUL_SEUIL, stroke: FACTURATION_CHART_OBJECTIF_STROKE },
]
