export const FINANCE_LINE_DEVIS_EXISTS = 'Un devis est déjà lié à cette ligne'
export const FINANCE_LINE_CREATED = 'Ligne de suivi créée'
export const FINANCE_LINE_DEVIS_GENERATED = 'Devis généré'
export const FINANCE_LINE_CANCELLED = 'Ligne annulée'
export const FINANCE_LINE_RESTORED = 'Ligne restaurée'
