export const INTERVIEW_TAB_EMPTY = 'Aucun entretien pour ce candidat.'
export const INTERVIEW_CONTACT_REQUIRED = 'Email ou téléphone requis'
export const INTERVIEW_DRAFT_OPEN = 'Un brouillon existe déjà.'
export const INTERVIEW_CTA = 'Nouvel entretien'
export const INTERVIEW_RESUME = 'Reprendre'
export const INTERVIEW_RESUME_DRAFT = 'Reprendre le brouillon'
export const INTERVIEW_ABANDON = 'Abandonner le brouillon'
export const INTERVIEW_START_SUBMIT = 'Lancer l’entretien'
export const INTERVIEW_START_PENDING = 'Ouverture…'
export const INTERVIEW_ABANDON_PENDING = 'Abandon…'
export const INTERVIEW_START_SUCCESS = 'Entretien ouvert'
export const INTERVIEW_ABANDON_SUCCESS = 'Brouillon abandonné'
export const INTERVIEW_START_SECTION = 'Identité'
export const INTERVIEW_START_HINT =
  'Confirme les infos minimales, puis ouvre le brouillon d’entretien.'
export const INTERVIEW_DRAFT_HINT = 'Les réponses s’enregistrent au fil de l’appel.'
export const INTERVIEW_NOT_DRAFT = 'Seuls les brouillons peuvent être enregistrés.'
export const INTERVIEW_ELIMINATOIRE = 'Éliminatoire'
export const INTERVIEW_NOTES = 'Note libre'
export const INTERVIEW_CHECKLIST_TITLE = 'Dossier documents'
export const INTERVIEW_NOTE_AUTOSAVE_MS = 800

