export const PUBLIC_APPLY_COPY = {
  brand: 'MediJob',
  title: 'Postuler',
  intro: 'Remplissez le formulaire — on vous recontacte rapidement.',
  unavailableTitle: 'Cette offre n’est plus disponible',
  unavailableBody: 'L’annonce a été retirée ou n’accepte plus de candidatures.',
  thanksTitle: 'C’est envoyé !',
  thanksBody: 'Votre candidature est bien arrivée chez MediJob. Un recruteur va la lire.',
  thanksHint: 'Pas besoin de renvoyer le même dossier.',
  submit: 'Envoyer ma candidature',
  submitting: 'Envoi…',
  consentPrefix: 'J’accepte le traitement de mes données (',
  consentLink: 'politique de confidentialité',
  consentRetention: ') — conservation',
  offerJob: 'Métier',
  offerCity: 'Ville',
  offerContract: 'Contrat',
  cvIdle: 'Déposer mon CV',
  cvChosen: 'CV sélectionné',
  cvHint: 'PDF, DOC ou DOCX · 5 Mo max · un clic ou glisser-déposer',
  fields: {
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    city: 'Ville',
    postalCode: 'Code postal',
    message: 'Message (optionnel)',
    cv: 'CV',
  },
} as const
