export const PUBLIC_APPLY_COPY = {
  brand: 'MediJob',
  title: 'Postuler',
  intro: 'Déposez votre candidature. Nous vous recontactons rapidement.',
  unavailableTitle: 'Cette offre n’est plus disponible',
  unavailableBody: 'L’annonce a été retirée ou n’accepte plus de candidatures.',
  thanksTitle: 'Merci, candidature bien reçue',
  thanksBody: 'L’équipe MediJob a bien reçu votre dossier.',
  submit: 'Envoyer ma candidature',
  submitting: 'Envoi…',
  consentPrefix: 'J’accepte le traitement de mes données conformément à la',
  consentLink: 'politique de confidentialité',
  consentRetention: 'Durée de conservation',
  offerJob: 'Métier',
  offerCity: 'Ville',
  offerContract: 'Contrat',
  fields: {
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    city: 'Ville',
    postalCode: 'Code postal',
    message: 'Message (optionnel)',
    cv: 'CV',
  },
} as const
