import { describe, expect, it } from 'vitest'
import { parseSyncroCandidatsRows } from './syncro-import-parse'

describe('parseSyncroCandidatsRows', () => {
  it('maps CANDIDATS header row + data into SyncroSheetRow', () => {
    const rows = parseSyncroCandidatsRows([
      [
        'ID',
        'TELEPHONE',
        'PRENOM',
        'NOM',
        'EMAIL',
        'PROFIL',
        'METIER',
        'NIVEAU',
        'CP',
        'VILLE',
        'REGION',
        'ZONE',
        'INSCRIT LE',
        'ADRESSE',
        'ETAPE BADAKAN',
        'VALIDE',
        'PAYS',
        'COMMENTAIRES',
        'SOURCE',
        'ATTRIBUE A',
        'STATUT',
        'DERNIER APPEL',
        'APPEL PAR',
        'RESULTAT',
        'RDV LE',
        'NOTES',
        'Fiche Emma',
        '_RELANCE',
      ],
      [
        'bk-1',
        '+336',
        'Marie',
        'App',
        'm@e.fr',
        'Préparateur',
        'Préparateur Expert',
        'Expert',
        75001,
        'Paris',
        'IDF',
        'IDF',
        null,
        '1 rue',
        'CREATED',
        'NON',
        'France',
        0,
        'Application',
        'Emma',
        'À appeler',
        null,
        null,
        'Messagerie',
        null,
        'note',
        null,
        null,
      ],
    ])
    expect(rows).toEqual([
      expect.objectContaining({
        id: 'bk-1',
        prenom: 'Marie',
        nom: 'App',
        telephone: '+336',
        email: 'm@e.fr',
        metier: 'Préparateur Expert',
        profil: 'Préparateur',
        ville: 'Paris',
        cp: '75001',
        statut: 'À appeler',
        resultat: 'Messagerie',
        attribueA: 'Emma',
        notes: 'note',
        valide: 'NON',
      }),
    ])
  })
})
