import { StyleSheet } from '@react-pdf/renderer'
import { PDF_BRAND } from './anonymized-profile-colors'

export const devisPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 0,
    paddingBottom: 52,
    fontFamily: 'Helvetica',
    color: PDF_BRAND.text,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    backgroundColor: PDF_BRAND.primary,
    paddingTop: 32,
    paddingBottom: 24,
    paddingHorizontal: 40,
  },
  brand: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#FFFFFF', letterSpacing: 0.6 },
  tagline: { marginTop: 4, fontSize: 9, color: PDF_BRAND.accent, letterSpacing: 0.8 },
  docMeta: { alignItems: 'flex-end' },
  docTitle: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: '#FFFFFF', letterSpacing: 1.4 },
  docDate: { marginTop: 6, fontSize: 9, color: PDF_BRAND.accent },
  accentBar: { height: 4, backgroundColor: PDF_BRAND.accent },
  body: { paddingTop: 28, paddingHorizontal: 40 },
  parties: { flexDirection: 'row', gap: 16, marginBottom: 22 },
  party: { flex: 1, padding: 14, backgroundColor: PDF_BRAND.muted },
  partyLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: PDF_BRAND.textMuted,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  partyName: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: PDF_BRAND.text },
  partySub: { marginTop: 4, fontSize: 10, color: PDF_BRAND.textMuted },
  object: { marginBottom: 18, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: PDF_BRAND.muted },
  objectLabel: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: PDF_BRAND.textMuted, letterSpacing: 1 },
  objectValue: { marginTop: 4, fontSize: 11, fontFamily: 'Helvetica-Bold' },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: PDF_BRAND.muted,
    paddingTop: 8,
    fontSize: 8,
    color: PDF_BRAND.textMuted,
  },
})
