-- Replace legacy ADMIN|RECRUTEUR with V1 four-role enum (fresh DB OK).
CREATE TYPE "UserRole_new" AS ENUM ('DIRECTION', 'RECRUTEUR', 'COMMUNICATION', 'RH_ADMIN');

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ALTER COLUMN "role" TYPE "UserRole_new" USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'RH_ADMIN'
    WHEN 'RECRUTEUR' THEN 'RECRUTEUR'
    WHEN 'DIRECTION' THEN 'DIRECTION'
    WHEN 'COMMUNICATION' THEN 'COMMUNICATION'
    WHEN 'RH_ADMIN' THEN 'RH_ADMIN'
    ELSE 'RECRUTEUR'
  END
)::"UserRole_new";

DROP TYPE "UserRole";

ALTER TYPE "UserRole_new" RENAME TO "UserRole";

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'RECRUTEUR'::"UserRole";
